# src/main.py
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from src.rag_pipeline import RAGPipeline
from config.settings import TOP_K, SIMILARITY_THRESHOLD

# ── Intent detection ────────────────────────────────────────────────────────
GREETINGS = {"hi", "hello", "hey", "helloo", "helo", "hii", "hiii", "namaste",
             "good morning", "good afternoon", "good evening", "sup", "yo"}

THANKS = {"thanks", "thank you", "thankyou", "thank u", "ty", "thx",
          "great", "awesome", "perfect", "helpful", "got it", "ok thanks"}

FAREWELLS = {"bye", "goodbye", "exit", "quit", "see you", "take care", "cya"}

ABOUT = {"who are you", "what are you", "what can you do",
         "help", "what do you know", "how can you help"}

def detect_intent(query: str) -> str | None:
    """Return intent name or None if it's a real college question."""
    q = query.lower().strip().rstrip("!?.")
    if q in GREETINGS or any(q.startswith(g) for g in GREETINGS):
        return "greeting"
    if q in THANKS:
        return "thanks"
    if q in FAREWELLS:
        return "farewell"
    if q in ABOUT:
        return "about"
    return None

def handle_intent(intent: str) -> str:
    responses = {
        "greeting": (
            "Hello! 👋 Welcome to the PDEA College Chatbot.\n"
            "I can help you with:\n"
            "  • Admissions & eligibility\n"
            "  • Courses & programs offered\n"
            "  • Fees & scholarships\n"
            "  • Hostel, placement, facilities\n\n"
            "What would you like to know?"
        ),
        "thanks": "You're welcome! 😊 Feel free to ask if you have more questions.",
        "farewell": "Goodbye! Best of luck with your admissions. 👋",
        "about": (
            "I'm the PDEA College Chatbot, powered by a RAG pipeline.\n"
            "I can answer questions about PDEA Pune colleges — "
            "admissions, courses, fees, placements, hostel, and more.\n"
            "Just ask me anything!"
        ),
    }
    return responses.get(intent, "")

# ── Response formatter ──────────────────────────────────────────────────────
def format_response(result: dict) -> str:
    source_labels = {
        "local":    "📚 From knowledge base",
        "gemini":   "🤖 Generated by Gemini AI",
        "fallback": "❓ No match found",
    }
    label = source_labels.get(result["source"], "")
    lines = [f"\n{label}", f"{result['answer']}"]

    if result["results"] and len(result["results"]) > 1:
        lines.append("\nRelated topics you might find useful:")
        for r in result["results"][1:]:
            lines.append(f"  [{r['score']:.2f}] {r['question']}")
    return "\n".join(lines)

# ── Main loop ───────────────────────────────────────────────────────────────
def main():
    print("=" * 55)
    print("  PDEA College Chatbot — RAG Pipeline")
    print(f"  Top-K: {TOP_K}  |  Threshold: {SIMILARITY_THRESHOLD}")
    print("  Type 'quit' to exit | 'debug' to toggle debug mode")
    print("=" * 55)

    print("\n[System] Loading RAG pipeline...")
    pipeline = RAGPipeline()
    print("[System] Ready. Say hello to get started!\n")

    debug_mode = False

    while True:
        try:
            query = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye!")
            break

        if not query:
            continue

        # Debug toggle
        if query.lower() == "debug":
            debug_mode = not debug_mode
            print(f"[Debug mode: {'ON' if debug_mode else 'OFF'}]")
            continue

        # ── Intent first ──────────────────────────────────────────────────
        intent = detect_intent(query)
        if intent == "farewell":
            print(f"Bot: {handle_intent(intent)}\n")
            break
        if intent:
            print(f"Bot: {handle_intent(intent)}\n")
            continue

        # ── RAG pipeline for real questions ───────────────────────────────
        result = pipeline.answer(query)

        if debug_mode:
            print(f"\n[DEBUG] Source: {result['source']}")
            for r in result["results"]:
                print(f"  Score {r['score']:.4f}: {r['question'][:65]}")

        print(f"Bot: {format_response(result)}\n")

if __name__ == "__main__":
    main()